// Re-exports the ELF + image ID generated by build.rs.
// When the "risc0" feature is enabled, include the generated bindings.
// Without it, provide stub constants so the crate compiles (the host
// will print a helpful error instead of calling these).

#[cfg(feature = "risc0")]
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

#[cfg(not(feature = "risc0"))]
pub const SHA256_PREIMAGE_ELF: &[u8] = &[];

#[cfg(not(feature = "risc0"))]
pub const SHA256_PREIMAGE_ID: [u32; 8] = [0; 8];
