// H.264 test corpus loader for milestone 3.
//
// Each fixture is an x264-encoded .h264 bitstream (M3-restricted
// flags: baseline, no B-frames, 1 ref, no 8x8 DCT, no deblocking,
// no CABAC, single I-frame) plus the matching ffmpeg-decoded raw
// YUV 4:2:0 output that the in-circuit decoder must reproduce
// bit-exactly.
//
// Generated by scripts/gen_h264_corpus.sh — re-run to refresh.
//
// All fixtures are committed to the repo so CI on machines without
// x264/ffmpeg can still run the regression tests.

#![cfg_attr(not(test), no_std)]

#[derive(Clone, Copy, Debug)]
pub struct Fixture {
    pub name: &'static str,
    pub width: u16,
    pub height: u16,
    pub qp: u8,
    /// The Annex-B framed H.264 bitstream as written by x264.
    pub h264: &'static [u8],
    /// Reference reconstructed YUV 4:2:0 as decoded by ffmpeg.
    /// (Y plane, then U at half-res, then V at half-res, byte-packed.)
    pub decoded_yuv: &'static [u8],
    /// Original raw YUV 4:2:0 input that was fed to x264.
    pub original_yuv: &'static [u8],
}

pub const NOISE_16X16_QP18: Fixture = Fixture {
    name: "noise-16x16-qp18",
    width: 16,
    height: 16,
    qp: 18,
    h264: include_bytes!("../fixtures/noise-16x16-qp18.h264"),
    decoded_yuv: include_bytes!("../fixtures/noise-16x16-qp18-decoded.yuv"),
    original_yuv: include_bytes!("../fixtures/noise-16x16.yuv"),
};

pub const ALL: &[Fixture] = &[NOISE_16X16_QP18];
